import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  textSubmitEdit: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 17,
  },
  btnSubmitEdit: {
    height: 45,
    backgroundColor: '#6600E7',
    alignSelf: 'center',
    width: 100,
    borderRadius: 5,
    elevation: 3,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  modalInputTask: {
    alignSelf: 'center',
    width: '80%',
    paddingHorizontal: 10,
    color: 'black',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  viewModal: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 20,
    elevation: 5,
    width: '80%',
    maxWidth: 480,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalBackdrop: {
    backgroundColor: 'black',
    opacity: 0.25,
    width: '100%',
    height: '100%',
    position: 'absolute',
  },
  viewTask: {
    flexDirection: 'row',
    alignItems: 'center',
    margin: 20,
  },
  btnOption: {
    backgroundColor: '#6600E7',
    width: 30,
    height: 30,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewLine: {
    height: 35,
    width: 2,
    backgroundColor: 'grey',
    marginHorizontal: 15,
  },
  textTaskTitle: {
    color: 'black',
    fontWeight: 'bold',
    fontSize: 16,
    flex: 1,
  },
  viewTaskDetail: {
    backgroundColor: 'white',
    padding: 20,
    elevation: 5,
    borderRadius: 20,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  container: {
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
  },
  viewHeader: {
    backgroundColor: '#6600E7',
    flexDirection: 'row',
    height: 50,
    alignItems: 'center',
    paddingLeft: 20,
    elevation: 3,
  },
  textHeader: {
    fontWeight: 'bold',
    fontSize: 17,
    color: 'white',
    marginLeft: 10,
  },
  btnAddTask: {
    width: 50,
    height: 50,
    borderRadius: 50 / 2,
    elevation: 5,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  viewTaskInput: {
    backgroundColor: '#ECECEC',
    elevation: 5,
    height: 50,
    borderRadius: 50 / 2,
    justifyContent: 'center',
    paddingHorizontal: 15,
    flex: 1,
  },
});

export default styles;
